owner: phoenix-net
repo: PhoenixNet-Status-Page

sites:
  - name: Synology NAS
    url: $NAS_URL
  - name: Paperless-NG
    url: $PAPERLESS_URL
  - name: CDN
    url: $CDN_URL
  - name: Plex
    check: "tcp-ping"
    url: $PLEX_URL
    port: 32400
  - name: DogCraft (Minecraft Server)
    check: "tcp-ping"
    url: $MC_URL
    port: 25565
  - name: Portfolio (PhoenixNet)
    url: $PORTFOLIO_URL
  - name: Contact Page
    url: $CONTACT_URL
  - name: OnlySheps
    url: $GAG_URL
  - name: Vaultwarden (Bitwarden)
    url: $VW_URL
  #- name: Vikunja ### DEPRECIATED
  #url: $VIKUNJA_URL
  - name: Focalboard
    url: $FB_URL
  
  # Change this one to a port eventually, please.
  - name: VPN Outside
    url: $OUTSIDEVPN_URL

status-website:
  cname: status.phoenixnet.tech
  logoUrl: https://phoenixsheppy.github.io/css/upptime/assets/pn-logo-sqr.png
  favicon: https://phoenixsheppy.github.io/css/upptime/assets/phoenixnet.ico
  name: PhoenixNet Status
  introTitle: "PhoenixNet Service Status Page"
  introMessage: Below is a list of services operated and maintained by PhoenixNet, along with their current status(es).
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://phoenixnet.tech
  links:
    - rel: stylesheet
      href: https://phoenixsheppy.github.io/css/upptime/DarkBlue.css
i18n:
  footer: ©️PhoenixNet 2021, Powered by [Upptime](https://upptime.js.org/).
  liveStatus: Service Status
  allSystemsOperational: All services are operational! 
